### ISSUE TITLE
Implement and configure SQLFluff in the repo

### ISSUE THREAD

**Issue by vvcb** [OHDSI/dbt-synthea#7]
The purpose of this task is to enforce consistent SQL syntax throughout the repo, amongst other benefits. See https://sqlfluff.com/

**Comment by vvcb** [comment]
@katy-sadowski , picking this task up from the Teams conversation. Happy to do this but should we wait until we have decided on the project directory structure and the _build up_ vs _break down_ strategy that we are finalising. Else we may end up with multiple unmerged PRs that will result in conflicts. Sqlfluff is already part of my _mega_ PR :wink: but happy to make a separate PR once we have settled on approach. Shouldn't take very long to do.

**Comment by katy-sadowski** [comment]
Thanks @vvcb !  Regarding directory structure - what are your thoughts on what I've put [here](https://github.com/OHDSI/dbt-synthea/pull/6) (plus an [Intermediate](https://docs.getdbt.com/best-practices/how-we-structure/3-intermediate) layer)?  Any additional decisions to make on directories besides this?

Regarding build up vs break down - can you please elaborate on what you mean by that?  Do you mean stuff like precommit hooks etc?

We can discuss it live next time we meet but I'm also happy to continue the convo here in the meantime :)

**Comment by vvcb** [comment]
@katy-sadowski , agree with moving the entire project to the root directory like you have done in your PR (and how it is in mine as well).

Regarding sub folders within the models folder, there are many ways to 'skin a cat' (never understood why there is one way let alone many but not sure where this phrase has come from).

In my team, we started with `source`, `staging`, ` vocab` and `omop` folders and then added a few more as the need arose. Within those folders, the models have a consistent naming convention. 

https://omop-lsc.surge.sh/rxn_dev/index.html#!/overview/dbt_omop

All this can get very complicated very quickly if we are not careful. So, starting simple (and starting itself) is a good thing and we can revisit frequently early and less frequently later.

In life and tech, I find [PEP 20](https://peps.python.org/pep-0020/) is a good anchor.

**Comment by katy-sadowski** [comment]
Thanks for the additional context!  For directory structure, I think let's stick with the dbt standard for now since we don't have a strong reason (yet) to deviate.  Looking to the future, I think this will also be the best starting point for a more generic ETL project.  

Regarding break down / build up - I am also starting to think it'll be easier to having the "skeleton" of the full ETL to work with vs starting with a blank slate.  Either way though I do think we should probably have targeted PRs for the bits of the "mega" PR we want to incorporate.  I'm not very familiar with SQLFluff, but my thinking in adding it in now was that we could ensure all SQL committed from the very beginning is linted and consistent.  Do you agree with that?

And then I'm thinking:

- create a convention-compliant base model for each Synthea table
- add in the intermediate and final model queries from your PR
  - convert to PostgreSQL
  - migrate to standard dbt folder structure
  - point at new base models
- gradually convert that "skeleton" ETL into our desired format & flow

Thoughts?
